# Generated by Django 5.1.6 on 2025-03-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_recipe_author_recipe_created_on_recipe_updated_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='recipe',
            name='update_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
